### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by laurentmuller** [vogellacompany/eclipsercp-jaxb-java11#2]
I tried your plugin. When I click on the "Trigger JAXB" button, the following error occurs:

```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2020-09-23 11:34:18.335
!MESSAGE Internal Error
!STACK 0
java.lang.ClassCastException: class org.eclipse.persistence.jaxb.JAXBContext cannot be cast to class javax.xml.bind.JAXBContext (org.eclipse.persistence.jaxb.JAXBContext is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2935fd2c; javax.xml.bind.JAXBContext is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6c6017b9)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:144)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:248)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:412)
       ...
```
It's a bit strange because the `org.eclipse.persistence.jaxb.JAXBContext` class is an instance of the ` javax.xml.bind.JAXBContext ` class.

**Comment by vogella** [comment]
Please reopen if you still can reproduce. Works fine for me.
